version: "3.9"

services:
  order-service:
    build:
      context: .
      dockerfile: ./build/order-service/Dockerfile
    container_name: order-service
    ports:
      - "9090:9090"
    # logs más legibles
    environment:
      - TZ=Etc/UTC

  api-gateway:
    build:
      context: .
      dockerfile: ./build/api-gateway/Dockerfile
    container_name: api-gateway
    depends_on:
      - order-service
    environment:
      # muy importante: el gateway ya no habla con localhost,
      # sino con el nombre del servicio dentro de la red de Docker
      - ORDER_SERVICE_ADDR=order-service:9090
      - TZ=Etc/UTC
    ports:
      - "8080:8080"
