version: "3.9"

services:
  api-gateway:
    build:
      context: .
      dockerfile: ./build/api-gateway/Dockerfile
    container_name: api-gateway
    depends_on:
      - order-service
    environment:
      - TZ=Etc/UTC
      - ORDER_SERVICE_ADDR=order-service:9090
      - PAYMENT_SERVICE_ADDR=payment-service:9091
      - INVENTORY_SERVICE_ADDR=inventory-service:9092
    ports:
      - "8080:8080"

  order-service:
    build:
      context: .
      dockerfile: ./build/order-service/Dockerfile
    container_name: order-service
    environment:
      - TZ=Etc/UTC
      - PORT=9090

  payment-service:
    build:
      context: .
      dockerfile: ./build/payment-service/Dockerfile
    container_name: payment-service
    # logs más legibles
    environment:
      - TZ=Etc/UTC
      - PORT=9091

  inventory-service:
    build:
      context: .
      dockerfile: ./build/inventory-service/Dockerfile
    container_name: inventory-service
    # logs más legibles
    environment:
      - TZ=Etc/UTC
      - PORT=9092
